<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'yii\\swiftmailer\\' => array($vendorDir . '/yiisoft/yii2-swiftmailer'),
    'yii\\jui\\' => array($vendorDir . '/yiisoft/yii2-jui'),
    'yii\\gii\\' => array($vendorDir . '/yiisoft/yii2-gii'),
    'yii\\faker\\' => array($vendorDir . '/yiisoft/yii2-faker'),
    'yii\\debug\\' => array($vendorDir . '/yiisoft/yii2-debug'),
    'yii\\composer\\' => array($vendorDir . '/yiisoft/yii2-composer'),
    'yii\\codeception\\' => array($vendorDir . '/yiisoft/yii2-codeception'),
    'yii\\bootstrap\\' => array($vendorDir . '/yiisoft/yii2-bootstrap'),
    'yii\\apidoc\\' => array($vendorDir . '/yiisoft/yii2-apidoc'),
    'yii\\' => array($vendorDir . '/yiisoft/yii2'),
    'miloschuman\\highcharts\\' => array($vendorDir . '/miloschuman/yii2-highcharts-widget/src'),
    'mdm\\admin\\' => array($vendorDir . '/mdmsoft/yii2-admin'),
    'kartik\\widgets\\' => array($vendorDir . '/kartik-v/yii2-widgets'),
    'kartik\\slider\\' => array($vendorDir . '/kartik-v/yii2-slider'),
    'kartik\\popover\\' => array($vendorDir . '/kartik-v/yii2-popover-x'),
    'kartik\\plugins\\rating\\' => array($vendorDir . '/kartik-v/bootstrap-star-rating'),
    'kartik\\plugins\\popover\\' => array($vendorDir . '/kartik-v/bootstrap-popover-x'),
    'kartik\\plugins\\fileinput\\' => array($vendorDir . '/kartik-v/bootstrap-fileinput'),
    'kartik\\plugins\\depdrop\\' => array($vendorDir . '/kartik-v/dependent-dropdown'),
    'kartik\\plugins\\dateformatter\\' => array($vendorDir . '/kartik-v/php-date-formatter'),
    'kartik\\plugins\\checkbox\\' => array($vendorDir . '/kartik-v/bootstrap-checkbox-x'),
    'kartik\\money\\' => array($vendorDir . '/kartik-v/yii2-money'),
    'kartik\\icons\\' => array($vendorDir . '/kartik-v/yii2-icons'),
    'kartik\\helpers\\' => array($vendorDir . '/kartik-v/yii2-helpers'),
    'kartik\\grid\\' => array($vendorDir . '/kartik-v/yii2-grid'),
    'kartik\\editable\\' => array($vendorDir . '/kartik-v/yii2-editable'),
    'kartik\\detail\\' => array($vendorDir . '/kartik-v/yii2-detail-view'),
    'kartik\\datecontrol\\' => array($vendorDir . '/kartik-v/yii2-datecontrol'),
    'kartik\\checkbox\\' => array($vendorDir . '/kartik-v/yii2-checkbox-x'),
    'kartik\\builder\\' => array($vendorDir . '/kartik-v/yii2-builder'),
    'hscstudio\\heart\\' => array($vendorDir . '/hscstudio/yii2-heart'),
    'cebe\\markdown\\latex\\' => array($vendorDir . '/cebe/markdown-latex'),
    'cebe\\markdown\\' => array($vendorDir . '/cebe/markdown'),
    'cebe\\jssearch\\' => array($vendorDir . '/cebe/js-search/lib'),
    'Fxp\\Composer\\AssetPlugin\\' => array($vendorDir . '/fxp/composer-asset-plugin'),
);
